apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-api
spec:
  selector:
    matchLabels:
      app: health-api
  replicas: 1
  template:
    metadata:
      labels:
        app: health-api
    spec:
      containers:
        - name: health-api
          image: sergiofdf/health-api:latest
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
          - name: https
            containerPort: 8081
          env:
          - name: KubernetesEnv
            value: "true"
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ConnectionStrings__PostgresConnection
            valueFrom:
              secretKeyRef:
                name: secrets-config
                key: connectionstring
          - name: RabbitMQConnection__Host
            valueFrom:
              secretKeyRef:
                name: secrets-config
                key: rabbitmqhost
          - name: RabbitMQConnection__Username
            valueFrom:
              secretKeyRef:
                name: secrets-config
                key: rabbitmqusername
          - name: RabbitMQConnection__Password
            valueFrom:
              secretKeyRef:
                name: secrets-config
                key: rabbitmqpassword
          - name: Jwt__Key
            valueFrom:
              secretKeyRef:
                name: secrets-config
                key: jwtkey      
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 20
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: health-api
spec:
  type: ClusterIP
  selector:
    app: health-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 8081
    targetPort: 8081
